site_name: Futures
site_url: https://alandefreitas.github.io/futures/
repo_url: https://github.com/alandefreitas/futures/
repo_name: alandefreitas/futures
site_description: "Futures: C++ Lock-Free Task Programming with ASIO executors"

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Motivation: motivation.md
  - Future types:
    - Concepts: future_concept.md
    - Launching tasks: launching.md
    - Stoppable futures: stoppable_futures.md
    - Shared futures: shared_futures.md
    - Waiting: waiting.md
  - Future Adaptors:
    - Continuations: continuations.md
    - Conjunctions: conjunctions.md
    - Disjunctions: disjunctions.md
  - Parallel Algorithms:
    - Algorithms: algorithms.md
    - Partitioners: partitioners.md
  # doxygen && rm -r reference && mkdir reference && doxybook2 --input ./xml --output ./reference --config ./.doxybook/config.json
  - Reference: # Reference is organized by module
    - Futures: reference/Modules/group__futures.md        # futures module
    - Adaptors: reference/Modules/group__adaptors.md      # adaptors module
    - Executors: reference/Modules/group__executors.md    # executors module
    - Algorithms: reference/Modules/group__algorithms.md  # algorithms module
    - Index: reference/Namespaces/namespacefutures.md      # The futures namespace contains everything
    - Classes: reference/Classes/index.md                  # All Classes
    - Files: reference/Files/index.md                      # All Files
  - Contributing: contributing.md
  - Acknowledgments: acknowledgments.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: futures
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/solid/code

edit_uri: ""

plugins:
  - search
  - mermaid2

extra:
  analytics:
    provider: google
    property: G-290016612

copyright: Copyright &copy; Alan Freitas

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://media.ethicalads.io/media/client/ethicalads.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css