site_name: Better Futures
site_url: https://alandefreitas.github.io/futures/
repo_url: https://github.com/alandefreitas/futures/
edit_uri: edit/develop/docs/
repo_name: alandefreitas/futures
site_description: "Better Futures: Because futures don't have to be awful"

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Motivation: motivation.md
  - Futures:
    - Basic Types: futures/future_types.md
    - Launching Tasks: futures/launching.md
    - Continuable Futures: futures/continuable_futures.md
    - Stoppable Futures: futures/stoppable_futures.md
    - Shared Futures: futures/shared_futures.md
    - Waiting for Futures: futures/waiting.md
    - Promises and Tasks: futures/promises.md
  - Future Adaptors:
    - Continuations: adaptors/continuations.md
    - Conjunctions: adaptors/conjunctions.md
    - Disjunctions: adaptors/disjunctions.md
    - Task Graphs: adaptors/task_graphs.md
  - Parallel Algorithms:
    - Algorithms: algorithms/algorithms.md
    - Partitioners: algorithms/partitioners.md
  - Networking:
    - Asio: networking/asio.md
  # doxygen && rm -r reference && mkdir reference && doxybook2 --input ./xml --output ./reference --config ./.doxybook/config.json
  - Reference: # Reference is organized by module
    - Configuration: config_reference.md                   # configuration options and macros
    - Futures: reference/Modules/group__futures.md         # futures module
    - Adaptors: reference/Modules/group__adaptors.md       # adaptors module
    - Executors: reference/Modules/group__executors.md     # executors module
    - Algorithms: reference/Modules/group__algorithms.md   # algorithms module
    - Index: reference/Namespaces/namespacefutures.md      # The futures namespace contains everything
    - Classes: reference/Classes/index.md                  # All Classes
    - Files: reference/Files/index.md                      # All Files
  - Contributing: contributing.md
  - Acknowledgments: acknowledgments.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: futures
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/solid/code



plugins:
  - search
  - macros:
      module_name: docs/macros
      include_dir: ..

extra:
  analytics:
    provider: google
    property: G-290016612

copyright: Copyright &copy; Alan Freitas

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://media.ethicalads.io/media/client/ethicalads.min.js
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css