blank_issues_enabled: false
contact_links:
  - name: Small Q&A 🙏
    url: https://github.com/alandefreitas/futures/discussions/new?category_id=31250560
    about: Please ask and answer questions here. Let's find out what's going on first.
  - name: Small Ideas 💡
    url: https://github.com/alandefreitas/futures/discussions/new?category_id=31250561
    about: Please discuss informal enhancement proposals here before creating an issue.
