# MIT License
# Copyright (c) 2021 Alan de Freitas

#[=======================================================================[.rst:
FindAsio
-------

FindAsio.cmake generated by cppm.

Finds the asio library as installed by cppm.
This file is generated by cppm because a asio-config.cmake is not available.

This script is intended as a modern CMake replacement for manual configuration.
It exposes for the main libraries that might be linked in the install directory as targets.
However, the script returns values that might be deprecated if asio ever produces a
asio-config.cmake with its installation.

About generated files
^^^^^^^^^^^^^^^^^^^^^

Note that find_package is case-sensitive while manifest package names are always lowercase.
- Default CMake package names tend to include lower and uppercase characters (i.e., "OpenCV")
  so there might be conflicts even in the generated package names. Thus, by default, if CMake provides
  a module FindFoo.cmake or the package provides its own foo-config.cmake, we don't generate any
  generated FindFoo.cmake. This is one more reason why the API of find modules might break if a
  generated package starts providing its own configuration files.
- However, find_package(foo) will also look for FindFoo.cmake, where the first char is uppercase.
  Thus, the generated file names uppercase the first char of package names to keep this CMake convention
  while the find_package command can still be find_package(foo). It's important to notice these scripts
  will always return lowercase targets to ensure consistency so you can later link foo::foo without
  worrying about case sensitivity.

User options
^^^^^^^^^^^^

Users should use the find_package command to use this file.

The minimal signature is:

find_package(asio)

The basic signature is:

find_package(<PackageName>
             [version]
             [EXACT]
             [QUIET]
             [MODULE]
             [REQUIRED]
             [[COMPONENTS] [components...]]
             [OPTIONAL_COMPONENTS components...]
             [NO_POLICY_SCOPE]
)

- VERSION: a single version "major[.minor[.patch[.tweak]]]" or a range "versionMin...[<]versionMax"
    - This file was generated because no asio-config.cmake was provided, which means a asio-version.cmake
      is very unlikely to be available.
    - If no config-file-version.cmake is provided, the configuration is assumed incompatible with any version requested
    - The only exception is when we have a cpp_modules directory layout, where this module will try to infer the
      version from the cpp_modules directory suffix. For instance, a package found in libgit/<version>/install
      is assumed to have version <version>.
    - Also note that CMake only supports core portion "major.minor.patch" of semver versions
      "major.minor.patch-pre-build" so only the core portion of semver version can be considered.
      This means there might some conflicts if the pre-release and release versions of the library with the
      same core are available.
    - This script can also infer the library version from a manifest file is installed in the <root>, <root>/shared,
      or <root>/lib directories.

The complete signature is:

find_package(<PackageName> [version] [EXACT] [QUIET]
             [REQUIRED] [[COMPONENTS] [components...]]
             [OPTIONAL_COMPONENTS components...]
             [CONFIG|NO_MODULE]
             [NO_POLICY_SCOPE]
             [NAMES name1 [name2 ...]]
             [CONFIGS config1 [config2 ...]]
             [HINTS path1 [path2 ... ]]
             [PATHS path1 [path2 ... ]]
             [PATH_SUFFIXES suffix1 [suffix2 ...]]
             [NO_DEFAULT_PATH]
             [NO_PACKAGE_ROOT_PATH]
             [NO_CMAKE_PATH]
             [NO_CMAKE_ENVIRONMENT_PATH]
             [NO_SYSTEM_ENVIRONMENT_PATH]
             [NO_CMAKE_PACKAGE_REGISTRY]
             [NO_CMAKE_BUILDS_PATH] # Deprecated; does nothing.
             [NO_CMAKE_SYSTEM_PATH]
             [NO_CMAKE_SYSTEM_PACKAGE_REGISTRY]
             [CMAKE_FIND_ROOT_PATH_BOTH |
              ONLY_CMAKE_FIND_ROOT_PATH |
              NO_CMAKE_FIND_ROOT_PATH])

The meaning of these parameters is available at: https://cmake.org/cmake/help/latest/command/find_package.html

Imported Targets
^^^^^^^^^^^^^^^^

This module provides the following imported targets, if found:

``asio::asio``
  The asio library

Result Variables
^^^^^^^^^^^^^^^^

This will define the following variables:

``asio_FOUND``
  True if the system has the asio library.
``asio_VERSION``
  The version of the asio library which was found.
``asio_INCLUDE_DIRS``
  Include directories needed to use asio.
``asio_LIBRARIES``
  Libraries needed to link to asio.

Cache Variables
^^^^^^^^^^^^^^^

The following cache variables may also be set:

``asio_INCLUDE_DIR``
  The directory containing ``foo.h``.
``asio_LIBRARY``
  The path to the asio library.

@see https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html

#]=======================================================================]

#######################################################
### Dev instructions: USER INPUT                    ###
#######################################################
# Users can set variables in the parent script to manipulate the behavior of
# find_package. Thus, these variables that should NOT be changed in this script.
# Besides the user parameters provided to find_package, this script will also
# consider these variables from the parent script.
# asio_DIR: The directory where we can find asio
# CMAKE_FIND_PACKAGE_SORT_ORDER: The preference order for versions (NONE, NAME (lexographically), NATURAL (VERSION_GREATER))
# CMAKE_FIND_PACKAGE_SORT_DIRECTION: How to order packager versions (DEC (default) or ASC (will return min version found))
# Variables that should NOT be used (users need them to manipulate behavior)
# asio_LIBRARY: The path of the library
# asio_Yy_LIBRARY: The path of library Yy provided by the module Xxx
# asio_INCLUDE_DIR: Where to find headers for using the library
# asio_Yy_INCLUDE_DIR: Where to find headers for using the library component Yy

#######################################################
### Dev instructions: CMAKE INPUT                   ###
#######################################################
# CMake transforms the user parameters given to find_packages into these variables
# CMAKE_FIND_PACKAGE_NAME: The <PackageName> which is searched for asio
# asio_FIND_REQUIRED: True if REQUIRED option was given
# asio_FIND_COMPONENTS: Required components
# asio_FIND_REQUIRED_<c>: True if component <c> was required
# asio_FIND_QUIETLY: True if QUIET option was given
# asio_CONSIDERED_CONFIGS: Config files considered by CMake
# asio_CONSIDERED_VERSIONS: Versions considered by CMake

# When a version is required:
# asio_FIND_VERSION: Full requested version string
# asio_FIND_MAJOR: Major version if requested, else 0
# asio_FIND_MINOR: Minor version if requested, else 0
# asio_FIND_PATCH: Patch version if requested, else 0
# asio_FIND_TWEAK: Tweak version if requested, else 0
# asio_FIND_VERSION_COUNT: Number of version components, 0 to 4
# asio_FIND_VERSION_EXACT: True if EXACT option was given

# When a version range was required:
# asio_FIND_VERSION_RANGE: Full requested version range string
# asio_FIND_VERSION_RANGE_MIN: Lower end point of the version range
# asio_FIND_VERSION_RANGE_MAX: Upper end point of the version range
# asio_FIND_VERSION_MIN: Full requested version string of the lower end point of the range
# asio_FIND_VERSION_MIN_MAJOR: Major version of the lower end point if requested (or 0)
# asio_FIND_VERSION_MIN_MINOR: Minor version of the lower end point if requested (or 0)
# asio_FIND_VERSION_MIN_PATCH: Patch version of the lower end point if requested (or 0)
# asio_FIND_VERSION_MIN_TWEAK: Major version of the lower end point if requested (or 0)
# asio_FIND_VERSION_MIN_COUNT: Number of version components in lower end point, 0 to 4
# asio_FIND_VERSION_RANGE_MAX: Lower end point of the version range
# asio_FIND_VERSION_RANGE_MAX: Upper end point of the version range
# asio_FIND_VERSION_MAX: Full requested version string of the upper end point of the range
# asio_FIND_VERSION_MAX_MAJOR: Major version of the upper end point if requested (or 0)
# asio_FIND_VERSION_MAX_MINOR: Minor version of the upper end point if requested (or 0)
# asio_FIND_VERSION_MAX_PATCH: Patch version of the upper end point if requested (or 0)
# asio_FIND_VERSION_MAX_TWEAK: Major version of the upper end point if requested (or 0)
# asio_FIND_VERSION_MAX_COUNT: Number of version components in upper end point, 0 to 4
# asio_FIND_VERSION_COMPLETE: full requested version string as specified (single or range)

#######################################################
### Macros                                          ###
#######################################################
# Print message if not in quiet mode
macro(asio_message _MSG)
    if (NOT asio_FIND_QUIETLY)
        message(STATUS
                "${CMAKE_CURRENT_LIST_FILE}(${CMAKE_CURRENT_LIST_LINE}): ${_MSG}")
    endif ()
endmacro()

macro(throw)
    message(FATAL_ERROR "asio not found")
endmacro()

macro(throw_if_required)
    if (asio_FIND_REQUIRED)
        throw()
    else ()
        asio_message("asio not found")
        return()
    endif ()
endmacro()

function(is_subdirectory BASEDIR SUBDIR RESULT)
    # Calculate absolute dirs
    file(REAL_PATH ${BASEDIR} BASEDIR)
    file(REAL_PATH ${SUBDIR} SUBDIR)
    # Check if subdir begins with basedir
    string(FIND ${SUBDIR} ${BASEDIR} SUBSTR_POS)
    if (SUBSTR_POS EQUAL 0)
        set(${RESULT} TRUE PARENT_SCOPE)
    else ()
        set(${RESULT} FALSE PARENT_SCOPE)
    endif ()
endfunction()

#######################################################
### Set some hint paths                             ###
#######################################################
# Initial hints
set(asio_INCLUDE_PATHS)
set(asio_INCLUDE_HINTS)

# If the user is using this script, it's very likely that it's also using cppm
# or a library that used cppm. This means asio_INSTALL_HINT should be set
# at this point and we also use it as a hint path.
if (asio_INSTALL_HINT)
    set(asio_INCLUDE_HINTS ${asio_INCLUDE_HINTS} ${asio_INSTALL_HINT} ${asio_INSTALL_HINT}/include)
endif ()

# Get some more hints from PkgConfig, if available
if (asio_FIND_QUIETLY)
    find_package(PkgConfig QUIET)
else ()
    find_package(PkgConfig)
endif ()
if (PKG_CONFIG_FOUND)
    # PKG_CONFIG_EXECUTABLE and PKG_CONFIG_VERSION_STRING should be set at this point

    # Check and maybe set the pkgconfig path
    if ($ENV{PKG_CONFIG_PATH})
        asio_message("PKG_CONFIG_PATH=$ENV{PKG_CONFIG_PATH}")
    elseif (asio_INSTALL_HINT)
        # If PKG_CONFIG_PATH is empty and we have an installation hint with a package config file
        if (EXISTS ${asio_INSTALL_HINT}/lib/pkgconfig)
            set(ENV{PKG_CONFIG_PATH} ${asio_INSTALL_HINT}/lib/pkgconfig)
        endif ()
    endif ()

    # Run pkgconfig
    pkg_check_modules(PC_asio QUIET asio)
    set(asio_INCLUDE_PATHS ${asio_INCLUDE_PATHS} ${PC_asio_INCLUDE_DIRS})
endif ()

#######################################################
### Look for packages candidates                    ###
#######################################################
find_path(asio_INCLUDE_DIR
        NAMES asio.hpp
        HINTS ${asio_INCLUDE_HINTS}
        PATHS ${asio_INCLUDE_PATHS}
        PATH_SUFFIXES include
        )

if (NOT asio_INCLUDE_DIR)
    throw_if_required()
endif ()

#######################################################
### Check versions                                  ###
#######################################################
# The package version might be available from pkgconfig or from the cppm directory layout
if (NOT asio_VERSION)
    if (PC_asio_VERSION)
        set(asio_VERSION ${PC_asio_VERSION})
    endif ()
endif ()

if (NOT asio_VERSION)
    if (asio_INSTALL_HINT)
        is_subdirectory(${asio_INSTALL_HINT} ${asio_INCLUDE_DIR} is_cppm_subdir)
        if (is_cppm_subdir)
            get_filename_component(asio_ALL_INSTALLS_PATH ${asio_INSTALL_HINT} DIRECTORY)
            get_filename_component(asio_VERSION_PATH ${asio_ALL_INSTALLS_PATH} DIRECTORY)
            get_filename_component(asio_VERSION ${asio_VERSION_PATH} NAME)
            if (NOT asio_VERSION VERSION_GREATER_EQUAL 0.0.0)
                unset(asio_VERSION)
            endif ()
        endif ()
    endif ()
endif ()

#######################################################
### Results                                         ###
#######################################################
# A find module should check if the values found are OK and set the following variables.
# FindPackageHandleStandardArgs will make most of the work here.
# Result variables find_package inherits from the from config script (returned to the user)
# Found:
#    asio_FOUND: Whether we found the module
#    asio_NOT_FOUND_MESSAGE: A message when not found. Use this instead of a message.
#    asio_Yy_FOUND: Whether we found the component Yy
#    asio_ROOT_DIR: Where to find the base directory of the module
# Headers:
#    asio_INCLUDE_DIRS: Optionally, the final set of include directories listed in one variable
#    asio_INCLUDE_DIR:
# Libraries
#     asio_RUNTIME_LIBRARY_DIRS: Optionally, PATH on windows or LD_LIBRARY_PATH on UNIX
#     asio_LIBRARIES: The libraries to use with the module
#     asio_LIBRARY_DIRS: Optionally, the final set of library directories listed in one variable for use by client code
# Definitions
#     asio_DEFINITIONS: The compile definitions to use when compiling code that uses the module
# Executables
#     asio_EXECUTABLE: The full absolute path to an executable.
#     asio_YYY_EXECUTABLE: The full absolute path to another executable where YYY is the tool name.
# Versions (if acceptable)
#     asio_VERSION: The version we found
#     asio_VERSION_VV: Variables of this form specify whether the Xxx module being provided is version VV of the module
#     asio_VERSION_MAJOR: major version component
#     asio_VERSION_MINOR: minor version component
#     asio_VERSION_PATCH: patch version component
#     asio_VERSION_TWEAK: tweak version component
#     asio_VERSION_COUNT: count of version components (0 to 4)

# FindPackageHandleStandardArgs will check if values are correct
# It ensures REQUIRED_VARS have valid values and asio_VERSION matches the requirements
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(asio
        FOUND_VAR asio_FOUND
        REQUIRED_VARS
        asio_INCLUDE_DIR
        VERSION_VAR asio_VERSION
        )

#######################################################
### Variable results                                ###
#######################################################
# Provide variables the user can user can use to link the library
if (asio_FOUND)
    set(asio_INCLUDE_DIRS ${asio_INCLUDE_DIR})
endif ()

#######################################################
### Target results                                  ###
#######################################################
# Provide targets the user can user can use to link the library
if (asio_FOUND AND NOT TARGET asio::asio)
    # Imported targets can be of unknown type
    add_library(asio::asio INTERFACE IMPORTED)
    set_target_properties(asio::asio PROPERTIES
            # IMPORTED_LOCATION "${asio_LIBRARY}"
            # INTERFACE_COMPILE_OPTIONS "${PC_asio_CFLAGS_OTHER}"
            INTERFACE_INCLUDE_DIRECTORIES "${asio_INCLUDE_DIR}"
            )
endif ()

# Hide cache variables
mark_as_advanced(
        asio_INCLUDE_DIR
)